### ISSUE TITLE
Unable to build models crate on develop branch

### ISSUE THREAD

**Issue by pmundt** [AmateurECE/redfish-codegen#11]
So I decided to try out migrating to the new models crate, but immediately ran into problems with the generator.

For starters, the 2.1.17-SNAPSHOT version of swagger-parser seems to no longer exist:

> [ERROR] Failed to execute goal on project redfish-codegen: Could not resolve dependencies for project com.twardyece.dmtf:redfish-codegen:jar:0.3.1-SNAPSHOT: Could not find artifact io.swagger.parser.v3:swagger-parser:jar:2.1.17-SNAPSHOT

Updating to 2.1.22 gets it building again:

```
--- a/redfish-generator/pom.xml
+++ b/redfish-generator/pom.xml
@@ -26,7 +26,7 @@
     <dependency>
       <groupId>io.swagger.parser.v3</groupId>
       <artifactId>swagger-parser</artifactId>
-      <version>2.1.17-SNAPSHOT</version>
+      <version>2.1.22</version>
     </dependency>
 
     <!-- https://mvnrepository.com/artifact/commons-cli/commons-cli -->
```

Next, I am flooded with these logger messages:

> [main] INFO com.twardyece.dmtf.openapi.DocumentParser - Inline schema created as Resource_Status_Conditions_inner. To have complete control of the model name, set the `title` field or provide a mapping using addInlineSchemaNameMapping()

After this, an all lowercase string trips up the PascalCase conversion:

> Exception in thread "main" com.twardyece.dmtf.text.ICaseConvertible$CaseConversionError: String inner is not convertible to PascalCase
	at com.twardyece.dmtf.text.PascalCaseName.<init>(PascalCaseName.java:97)
	at com.twardyece.dmtf.specification.UnversionedSchemaIdentifier.<init>(UnversionedSchemaIdentifier.java:22)
	at com.twardyece.dmtf.model.mapper.UnversionedModelTypeMapper.matchesType(UnversionedModelTypeMapper.java:18)
	at com.twardyece.dmtf.model.ModelResolver.resolvePath(ModelResolver.java:76)
	at com.twardyece.dmtf.model.ModelResolver.resolveSchema(ModelResolver.java:114)
	at com.twardyece.dmtf.model.ModelResolver.resolveSchema(ModelResolver.java:117)
	at com.twardyece.dmtf.model.context.factory.StructContextFactory.toProperty(StructContextFactory.java:43)
	at com.twardyece.dmtf.model.context.factory.StructContextFactory.lambda$makeModelContext$0(StructContextFactory.java:28)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.twardyece.dmtf.model.context.factory.StructContextFactory.makeModelContext(StructContextFactory.java:29)
	at com.twardyece.dmtf.FileFactory.makeModelFile(FileFactory.java:40)
	at com.twardyece.dmtf.RedfishCodegen.buildModels(RedfishCodegen.java:182)
	at com.twardyece.dmtf.RedfishCodegen.generate(RedfishCodegen.java:334)
	at com.twardyece.dmtf.RedfishCodegen.main(RedfishCodegen.java:404)
make: *** [generate.mk:45: redfish-models/src/lib.rs] Error 1

I tried a naive fix for this, which is probably wrong, but seems to get things progressing a bit more:

```
--- a/redfish-generator/src/main/java/com/twardyece/dmtf/text/PascalCaseName.java
+++ b/redfish-generator/src/main/java/com/twardyece/dmtf/text/PascalCaseName.java
@@ -1,5 +1,7 @@
 package com.twardyece.dmtf.text;
 
+import org.apache.commons.lang3.StringUtils;
+
 import java.util.ArrayList;
 import java.util.Collection;
 import java.util.List;
@@ -15,7 +17,15 @@ public class PascalCaseName implements ICaseConvertible, Comparable<PascalCaseNa
         // in PascalCase, e.g. abbreviations like "PCIe", we have to intentionally handle those before attempting to
         // parse the identifier(s) as PascalCase.
         ArrayList<String> identifiers = new ArrayList<>();
-        identifiers.add(name);
+
+       // Check for the corner case where the string is entirely lower case
+        if (StringUtils.isAllLowerCase(name)) {
+            String identifier = StringUtils.capitalize(name);
+            identifiers.add(identifier);
+        } else {
+            identifiers.add(name);
+        }
+
         int discoveredLength = 0;
         while (discoveredLength < name.length()) {
             String identifier = identifiers.get(identifiers.size() - 1);
```

The next case that blows up is a case conversion for a numeric string:

> main] INFO com.twardyece.dmtf.model.context.factory.UnitContextFactory - Creating unit struct for crate::models::storage::StorageController
Exception in thread "main" com.twardyece.dmtf.text.ICaseConvertible$CaseConversionError: String 1 is not convertible to PascalCase
	at com.twardyece.dmtf.text.PascalCaseName.<init>(PascalCaseName.java:94)
	at com.twardyece.dmtf.specification.UnversionedSchemaIdentifier.<init>(UnversionedSchemaIdentifier.java:22)
	at com.twardyece.dmtf.model.mapper.UnversionedModelTypeMapper.matchesType(UnversionedModelTypeMapper.java:18)
	at com.twardyece.dmtf.model.ModelResolver.resolvePath(ModelResolver.java:76)
	at com.twardyece.dmtf.model.ModelResolver.resolveSchema(ModelResolver.java:114)
	at com.twardyece.dmtf.model.context.factory.StructContextFactory.toProperty(StructContextFactory.java:43)
	at com.twardyece.dmtf.model.context.factory.StructContextFactory.lambda$makeModelContext$0(StructContextFactory.java:28)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.twardyece.dmtf.model.context.factory.StructContextFactory.makeModelContext(StructContextFactory.java:29)
	at com.twardyece.dmtf.FileFactory.makeModelFile(FileFactory.java:40)
	at com.twardyece.dmtf.RedfishCodegen.buildModels(RedfishCodegen.java:182)
	at com.twardyece.dmtf.RedfishCodegen.generate(RedfishCodegen.java:334)
	at com.twardyece.dmtf.RedfishCodegen.main(RedfishCodegen.java:404)
make: *** [generate.mk:45: redfish-models/src/lib.rs] Error 1

And my attempt to work around this:

```
--- a/redfish-generator/src/main/java/com/twardyece/dmtf/text/PascalCaseName.java
+++ b/redfish-generator/src/main/java/com/twardyece/dmtf/text/PascalCaseName.java
@@ -79,7 +89,8 @@ public class PascalCaseName implements ICaseConvertible, Comparable<PascalCaseNa
 
         if (identifiers.size() > 0) {
             String identifier = identifiers.get(0);
-            if (!Abbreviation.SPECIAL_ABBREVIATIONS.containsKey(identifier) && !Character.isUpperCase(identifier.charAt(0))) {
+            char c = identifier.charAt(0);
+            if (!Abbreviation.SPECIAL_ABBREVIATIONS.containsKey(identifier) && Character.isAlphabetic(c) && !Character.isUpperCase(c)) {
                 throw new CaseConversionError("PascalCase", name);
             }
         }
```
This was clearly not the correct fix, as the matcher then ends up blowing the stack:

> [main] INFO com.twardyece.dmtf.model.context.factory.UnitContextFactory - Creating unit struct for crate::models::zone::v1_6_3::Zone
Exception in thread "main" java.lang.StackOverflowError
	at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4329)
	at java.base/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3955)
	at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4329)
	at java.base/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3955)
	at java.base/java.util.regex.Pattern$Start.match(Pattern.java:3608)
	at java.base/java.util.regex.Matcher.search(Matcher.java:1728)
	at java.base/java.util.regex.Matcher.find(Matcher.java:745)
	at com.twardyece.dmtf.specification.VersionedSchemaIdentifier.isVersion(VersionedSchemaIdentifier.java:43)
	at com.twardyece.dmtf.model.mapper.VersionedModelTypeMapper.matchesName(VersionedModelTypeMapper.java:38)
	at com.twardyece.dmtf.model.ModelResolver.reverseResolveIdentifier(ModelResolver.java:95)
	at com.twardyece.dmtf.policies.AdditionalModelAttributesPolicy.lambda$applyToProperties$0(AdditionalModelAttributesPolicy.java:60)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.twardyece.dmtf.policies.AdditionalModelAttributesPolicy.applyToProperties(AdditionalModelAttributesPolicy.java:59)
	at com.twardyece.dmtf.policies.AdditionalModelAttributesPolicy.lambda$applyToProperties$0(AdditionalModelAttributesPolicy.java:62)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.twardyece.dmtf.policies.AdditionalModelAttributesPolicy.applyToProperties(AdditionalModelAttributesPolicy.java:59)
	at com.twardyece.dmtf.policies.AdditionalModelAttributesPolicy.lambda$applyToProperties$0(AdditionalModelAttributesPolicy.java:62)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        .....
make: *** [generate.mk:45: redfish-models/src/lib.rs] Error 1

If any of my fixes are correct, I can check them in and send you a PR, but I'm otherwise stuck at this point. Any ideas on how to proceed?

**Comment by AmateurECE** [comment]
Oh no, I'm sorry to hear this! I'll take a closer look tonight and get back to you. All these fixes seem sane, but I'd like to try recreating the failures you were seeing to provide insight on how to proceed.

I'll admit that I haven't ever tried to run the parser with swagger-parser v2.1.22. I was experiencing issues with 2.1.17 that I had traced down to swagger-api/swagger-parser#1961, but the PR I opened for that issue has gone stale. I will try with newer versions tonight to see whether that issue has been resolved without my PR being merged.

> After this, an all lowercase string trips up the PascalCase conversion:

This feels like perhaps a typo in the DMTF schema, but I will investigate to see whether I think that's the case. There are a few of these I've found while developing this tool, and I've been opening issues with the DMTF as I discover them to get them resolved. This might be a new one. So far, my strategy has been to prefer patching the schemas to making code changes when there's an obvious inconsistency in the schema.

I'll take a look as soon as I can and get back to you!

**Comment by AmateurECE** [comment]
As an interim workaround, you should be able to build and install this branch into your local maven cache:
https://github.com/AmateurECE/swagger-parser/tree/bugfix/issue-1961

That should give you a version of 2.1.17-SNAPSHOT that can be used to build the models.

**Comment by AmateurECE** [comment]
@pmundt can you confirm for me which release of the Redfish schemas you're generating from, and how you're running the generator in this case? I was able to generate models for 2023.1 using swagger-parser v2.1.22 and the `generate.mk` script (I realize those schemas are quite old now, I will soon try generating newer models). Although, I did still experience the swagger-parser issue I mentioned previously. Do you have any local custom schemas or modifications?

Log from the build:
[build.log](https://github.com/user-attachments/files/16522643/build.log)

**Comment by pmundt** [comment]
Ah, yes, I forgot to mention that I was trying out the newer releases:

RELEASE_VERSION=2024.1
SWORDFISH_VERSION=v1.2.6

sorry for the confusion.

My current workflow is:

```
$ tools/genpatch.sh
$ cd redfish-generator
$ mvn clean package
$ cd ../redfish-models
$ make -C .. -f generate.mk models
```

Using a clean checkout + updated version of coreutils + latest rustc I was finally able to get it built with swagger-parser v2.1.22 as well. I'll send a separate PR to bump up the swagger-parser version.

That being said, I haven't had any luck with just running `cargo build` at the top-level, hence I've been carrying out the `build.rs` steps manually. Here's the log from the top-level build:
[cargo-build.log](https://github.com/user-attachments/files/16529001/cargo-build.log)

Once I've generated the models by hand cargo build works as expected.

With those updates in place, I will try again with the newer schemas and see if the same issues persist. Pending that, we can either close this issue after bumping the swagger-parser version, or repurpose the issue to track the status of the integration of the newer schemas.

**Comment by pmundt** [comment]
With the schema version bumped up as above, I run back in to the same issue:

```
[main] INFO com.twardyece.dmtf.model.context.factory.UnitContextFactory - Creating unit struct for crate::models::storage::StorageController
Exception in thread "main" com.twardyece.dmtf.text.ICaseConvertible$CaseConversionError: String 1 is not convertible to PascalCase
	at com.twardyece.dmtf.text.PascalCaseName.<init>(PascalCaseName.java:83)
	at com.twardyece.dmtf.specification.UnversionedSchemaIdentifier.<init>(UnversionedSchemaIdentifier.java:22)
	at com.twardyece.dmtf.model.mapper.UnversionedModelTypeMapper.matchesType(UnversionedModelTypeMapper.java:18)
	at com.twardyece.dmtf.model.ModelResolver.resolvePath(ModelResolver.java:76)
	at com.twardyece.dmtf.model.ModelResolver.resolveSchema(ModelResolver.java:114)
	at com.twardyece.dmtf.model.context.factory.StructContextFactory.toProperty(StructContextFactory.java:43)
	at com.twardyece.dmtf.model.context.factory.StructContextFactory.lambda$makeModelContext$0(StructContextFactory.java:28)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.twardyece.dmtf.model.context.factory.StructContextFactory.makeModelContext(StructContextFactory.java:29)
	at com.twardyece.dmtf.FileFactory.makeModelFile(FileFactory.java:40)
	at com.twardyece.dmtf.RedfishCodegen.buildModels(RedfishCodegen.java:182)
	at com.twardyece.dmtf.RedfishCodegen.generate(RedfishCodegen.java:334)
	at com.twardyece.dmtf.RedfishCodegen.main(RedfishCodegen.java:404)
make: *** [generate.mk:45: redfish-models/src/lib.rs] Error 1
```

**Comment by AmateurECE** [comment]
Ah, that's no problem, thank you for the context! By changing to the 2024.1 schemas, I've been able to reproduce these exact messages. I'm investigating, I will get back to you when I've got a path forward!
